language: node_js
node_js:
 - "4"
script: make test-ci
services:
  - redis
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
  apt:
    packages:
      - redis
      - mongodb-org
      - graphicsmagick
sudo: false
