language: node_js
node_js:
 - "4"
script: make test-ci
services:
  - redis
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
      - ubuntu-toolchain-r-test
    packages:
      - redis-server
      - mongodb-org
      - graphicsmagick
      - g++-4.8
env:
  - CXX=g++-4.8
sudo: false
