users:
  tracker:
    menu:
      forum_topic:
        priority: 10

  subscriptions:
    forum_topic:
      to_type: FORUM_TOPIC
      priority: 10
    forum_section:
      to_type: FORUM_SECTION
      priority: 20
