setting_schemas:
  forum_usergroup:

    forum_show:
      extends: true

    forum_read_topics:
      extends: true

    forum_reply_topics:
      extends: true

    forum_start_topics:
      extends: true
