setting_schemas:
  section_usergroup:
    forum_can_view:
      extends: true
      priority: 10

    forum_can_reply:
      extends: true
      priority: 20

    forum_can_start_topics:
      extends: true
      priority: 30

    forum_edit_max_time:
      extends: true
      priority: 40
