setting_schemas:
  forumgroups:

    forum_can_list_threads:
      extends: true

    forum_can_read_threads:
      extends: true

    forum_can_reply_threads:
      extends: true

    forum_can_create_threads:
      extends: true
